# filepath: /Users/levi.bostian/code/Multi-Module-Android-dev-environment-lib/.github/workflows/snapshots.yml
name: Publish Snapshot to GitHub Packages

on:
  push:
    branches-ignore:
      - main

jobs:
  publish-snapshot:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Set snapshot version from branch name
        id: vars
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          SNAPSHOT_VERSION="${BRANCH_NAME}-SNAPSHOT"
          echo "SNAPSHOT_VERSION=$SNAPSHOT_VERSION" >> $GITHUB_ENV
      - name: Publish to GitHub Packages
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ env.SNAPSHOT_VERSION }}
        run: ./gradlew :logger-module:publishLoggerPublicationToGitHubPackagesRepository
